version: 2.1

orbs:
  architect: giantswarm/architect@0.10.1

jobs:
  build:
    machine:
      image: "ubuntu-1604:201903-01"
    environment:

      # Set this to the upstream version tag to use/build
      UPSTREAM_TAG: v1.7.0-rc1

    steps:
      - checkout

      - run:
          name: Clone upstream repository
          command:
            git clone -b $UPSTREAM_TAG --depth 1 https://github.com/aws/amazon-vpc-cni-k8s.git

      - run:
          name: Build Docker image
          command:
            cd amazon-vpc-cni-k8s && make docker

      - run:
          name: Tag the image according to Giant Swarm convention
          command:
            docker tag amazon/amazon-k8s-cni:$UPSTREAM_TAG quay.io/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - architect/push-to-docker:
          context: "architect"
          name: "push-to-quay"
          image: "quay.io/giantswarm/aws-cni"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
